language: csharp
dist: trusty
sudo: required
mono: none
dotnet: 2.1.300
solution: JsonFlatFileDataStore.sln
script:
  - dotnet restore
  - dotnet build
  - dotnet test JsonFlatFileDataStore.Test/JsonFlatFileDataStore.Test.csproj